export type Video = {
  id: string;
  title: string;
  description: string;
  date: string;
  youtubeId: string;
  href: string;
  duration: string;
  source: string;
};

/** Full Legal Guide Philippines catalog (YouTube @LegalGuidePhilippines).
 *  Upload dates unavailable from flat playlist — `date` is synthetic
 *  (descending by playlist order, newest first) for stable sorting only.
 */
export const videos: Video[] = [
  {
    id: "YrdApjirNS8",
    title: "Don't Panic! Why You Get BIR Notices Even Without Sales",
    description: "A Legal Guide Philippines explainer: Don't Panic! Why You Get BIR Notices Even Without Sales.",
    date: "2026-09-03",
    youtubeId: "YrdApjirNS8",
    href: "https://www.youtube.com/watch?v=YrdApjirNS8",
    duration: "10:43",
    source: "Legal Guide Philippines",
  },
  {
    id: "dQErmsY8-ng",
    title: "Right Way to Understand Just Cause Termination",
    description: "A Legal Guide Philippines explainer: Right Way to Understand Just Cause Termination.",
    date: "2026-09-02",
    youtubeId: "dQErmsY8-ng",
    href: "https://www.youtube.com/watch?v=dQErmsY8-ng",
    duration: "6:41",
    source: "Legal Guide Philippines",
  },
  {
    id: "Mz2AuCOQwsU",
    title: "WITHHOLDING TAX: BAKIT MAY KALTAS ANG SWELDO KO!?",
    description: "A Legal Guide Philippines explainer: WITHHOLDING TAX: BAKIT MAY KALTAS ANG SWELDO KO!?.",
    date: "2026-09-01",
    youtubeId: "Mz2AuCOQwsU",
    href: "https://www.youtube.com/watch?v=Mz2AuCOQwsU",
    duration: "12:45",
    source: "Legal Guide Philippines",
  },
  {
    id: "Wt6okpsnz84",
    title: "Bakit mahalaga ang due process bago tanggalin ang empleyado?",
    description: "A Legal Guide Philippines explainer: Bakit mahalaga ang due process bago tanggalin ang empleyado?.",
    date: "2026-08-31",
    youtubeId: "Wt6okpsnz84",
    href: "https://www.youtube.com/watch?v=Wt6okpsnz84",
    duration: "0:54",
    source: "Legal Guide Philippines",
  },
  {
    id: "sy2ySNqRMmQ",
    title: "Is It Better to Sell or Donate an Estate?",
    description: "A Legal Guide Philippines explainer: Is It Better to Sell or Donate an Estate?.",
    date: "2026-08-30",
    youtubeId: "sy2ySNqRMmQ",
    href: "https://www.youtube.com/watch?v=sy2ySNqRMmQ",
    duration: "19:16",
    source: "Legal Guide Philippines",
  },
  {
    id: "79FDpL4QrDY",
    title: "May Black Sheep Ka Ba Sa Family? (Legal Rules on Disinheritance!)",
    description: "A Legal Guide Philippines explainer: May Black Sheep Ka Ba Sa Family? (Legal Rules on Disinheritance!).",
    date: "2026-08-29",
    youtubeId: "79FDpL4QrDY",
    href: "https://www.youtube.com/watch?v=79FDpL4QrDY",
    duration: "10:02",
    source: "Legal Guide Philippines",
  },
  {
    id: "o9IiqWverwo",
    title: "My Client Caught a Thief, But Did the Right Thing",
    description: "A Legal Guide Philippines explainer: My Client Caught a Thief, But Did the Right Thing.",
    date: "2026-08-28",
    youtubeId: "o9IiqWverwo",
    href: "https://www.youtube.com/watch?v=o9IiqWverwo",
    duration: "0:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "iwQBvadf2Zc",
    title: "INCOME WHILE ABROAD - Taxable ba income ko as an OFW?",
    description: "A Legal Guide Philippines explainer: INCOME WHILE ABROAD - Taxable ba income ko as an OFW?.",
    date: "2026-08-27",
    youtubeId: "iwQBvadf2Zc",
    href: "https://www.youtube.com/watch?v=iwQBvadf2Zc",
    duration: "18:37",
    source: "Legal Guide Philippines",
  },
  {
    id: "PtcbMOb2WDg",
    title: "Bakit ako nagbayad kahit nagnakaw siya? (The \"Win Twice\" Rule)",
    description: "A Legal Guide Philippines explainer: Bakit ako nagbayad kahit nagnakaw siya? (The \"Win Twice\" Rule).",
    date: "2026-08-26",
    youtubeId: "PtcbMOb2WDg",
    href: "https://www.youtube.com/watch?v=PtcbMOb2WDg",
    duration: "8:18",
    source: "Legal Guide Philippines",
  },
  {
    id: "8u_f58PaQcg",
    title: "YOUR TaxTIKA -  FLAT OR GRADUATED INCOME TAX RATE???",
    description: "A Legal Guide Philippines explainer: YOUR TaxTIKA -  FLAT OR GRADUATED INCOME TAX RATE???.",
    date: "2026-08-25",
    youtubeId: "8u_f58PaQcg",
    href: "https://www.youtube.com/watch?v=8u_f58PaQcg",
    duration: "22:01",
    source: "Legal Guide Philippines",
  },
  {
    id: "tgAJCBhL38c",
    title: "THE RAKET REALITY - TAXABLE BA SIDELINE MO?",
    description: "A Legal Guide Philippines explainer: THE RAKET REALITY - TAXABLE BA SIDELINE MO?.",
    date: "2026-08-24",
    youtubeId: "tgAJCBhL38c",
    href: "https://www.youtube.com/watch?v=tgAJCBhL38c",
    duration: "21:33",
    source: "Legal Guide Philippines",
  },
  {
    id: "px1SFjU7-S0",
    title: "LGPH Show: May karapatan ba magmana ang Illegitimate Child?",
    description: "A Legal Guide Philippines explainer: LGPH Show: May karapatan ba magmana ang Illegitimate Child?.",
    date: "2026-08-23",
    youtubeId: "px1SFjU7-S0",
    href: "https://www.youtube.com/watch?v=px1SFjU7-S0",
    duration: "27:23",
    source: "Legal Guide Philippines",
  },
  {
    id: "no3PZOBorBw",
    title: "LGPH Show: Kung ampon ka, may karapatan ka ba magmana?",
    description: "A Legal Guide Philippines explainer: LGPH Show: Kung ampon ka, may karapatan ka ba magmana?.",
    date: "2026-08-22",
    youtubeId: "no3PZOBorBw",
    href: "https://www.youtube.com/watch?v=no3PZOBorBw",
    duration: "22:44",
    source: "Legal Guide Philippines",
  },
  {
    id: "QYpAPQNp8T8",
    title: "\"I Own the Land, But Can’t Find the Title—What Now?\"",
    description: "A Legal Guide Philippines explainer: \"I Own the Land, But Can’t Find the Title—What Now?\".",
    date: "2026-08-21",
    youtubeId: "QYpAPQNp8T8",
    href: "https://www.youtube.com/watch?v=QYpAPQNp8T8",
    duration: "20:58",
    source: "Legal Guide Philippines",
  },
  {
    id: "uK78VGxDgnQ",
    title: "Do I really need a company manual?? or can i just make rules as needed",
    description: "A Legal Guide Philippines explainer: Do I really need a company manual?? or can i just make rules as needed.",
    date: "2026-08-20",
    youtubeId: "uK78VGxDgnQ",
    href: "https://www.youtube.com/watch?v=uK78VGxDgnQ",
    duration: "28:34",
    source: "Legal Guide Philippines",
  },
  {
    id: "aUAVBL2ecpM",
    title: "ESTATE TAX AMNESTY ENDS JUNE 14! DON'T MISS OUT!",
    description: "A Legal Guide Philippines explainer: ESTATE TAX AMNESTY ENDS JUNE 14! DON'T MISS OUT!.",
    date: "2026-08-19",
    youtubeId: "aUAVBL2ecpM",
    href: "https://www.youtube.com/watch?v=aUAVBL2ecpM",
    duration: "28:10",
    source: "Legal Guide Philippines",
  },
  {
    id: "5R_etJt63V8",
    title: "When employees file labor cases against their employers",
    description: "A Legal Guide Philippines explainer: When employees file labor cases against their employers.",
    date: "2026-08-18",
    youtubeId: "5R_etJt63V8",
    href: "https://www.youtube.com/watch?v=5R_etJt63V8",
    duration: "31:43",
    source: "Legal Guide Philippines",
  },
  {
    id: "yYYCig71jgw",
    title: "Estate Settlement: Who inherits in the Philippines",
    description: "A Legal Guide Philippines explainer: Estate Settlement: Who inherits in the Philippines.",
    date: "2026-08-17",
    youtubeId: "yYYCig71jgw",
    href: "https://www.youtube.com/watch?v=yYYCig71jgw",
    duration: "38:03",
    source: "Legal Guide Philippines",
  },
  {
    id: "zTXPb1tk9A0",
    title: "Awol After Resignation",
    description: "A Legal Guide Philippines explainer: Awol After Resignation.",
    date: "2026-08-16",
    youtubeId: "zTXPb1tk9A0",
    href: "https://www.youtube.com/watch?v=zTXPb1tk9A0",
    duration: "8:57",
    source: "Legal Guide Philippines",
  },
  {
    id: "ljCLmRX6wZo",
    title: "Why AWOL happens?",
    description: "A Legal Guide Philippines explainer: Why AWOL happens?.",
    date: "2026-08-15",
    youtubeId: "ljCLmRX6wZo",
    href: "https://www.youtube.com/watch?v=ljCLmRX6wZo",
    duration: "8:56",
    source: "Legal Guide Philippines",
  },
  {
    id: "wSWJs9EKLTM",
    title: "Can boss refuse my resignation?",
    description: "A Legal Guide Philippines explainer: Can boss refuse my resignation?.",
    date: "2026-08-14",
    youtubeId: "wSWJs9EKLTM",
    href: "https://www.youtube.com/watch?v=wSWJs9EKLTM",
    duration: "8:11",
    source: "Legal Guide Philippines",
  },
  {
    id: "T0DWapsQD-4",
    title: "Why Do I Need an Affidavit of Loss?",
    description: "A Legal Guide Philippines explainer: Why Do I Need an Affidavit of Loss?.",
    date: "2026-08-13",
    youtubeId: "T0DWapsQD-4",
    href: "https://www.youtube.com/watch?v=T0DWapsQD-4",
    duration: "5:32",
    source: "Legal Guide Philippines",
  },
  {
    id: "RSKqjPBCh5w",
    title: "Implications of Special Power of Attorney (SPA) to a Non-Individual",
    description: "A Legal Guide Philippines explainer: Implications of Special Power of Attorney (SPA) to a Non-Individual.",
    date: "2026-08-12",
    youtubeId: "RSKqjPBCh5w",
    href: "https://www.youtube.com/watch?v=RSKqjPBCh5w",
    duration: "10:35",
    source: "Legal Guide Philippines",
  },
  {
    id: "WlARP2UcgKE",
    title: "What is a promissory note and why do you need one?",
    description: "A Legal Guide Philippines explainer: What is a promissory note and why do you need one?.",
    date: "2026-08-11",
    youtubeId: "WlARP2UcgKE",
    href: "https://www.youtube.com/watch?v=WlARP2UcgKE",
    duration: "7:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "5AxiEwMMw0Y",
    title: "Ano nga ba ang SPA ?",
    description: "A Legal Guide Philippines explainer: Ano nga ba ang SPA ?.",
    date: "2026-08-10",
    youtubeId: "5AxiEwMMw0Y",
    href: "https://www.youtube.com/watch?v=5AxiEwMMw0Y",
    duration: "6:31",
    source: "Legal Guide Philippines",
  },
  {
    id: "8rSWeFVspA4",
    title: "My deceased parents didn't leave a will. Should I be worried?",
    description: "A Legal Guide Philippines explainer: My deceased parents didn't leave a will. Should I be worried?.",
    date: "2026-08-09",
    youtubeId: "8rSWeFVspA4",
    href: "https://www.youtube.com/watch?v=8rSWeFVspA4",
    duration: "5:55",
    source: "Legal Guide Philippines",
  },
  {
    id: "NgdZ-dbhua8",
    title: "How to choose a representative for estate settlement",
    description: "A Legal Guide Philippines explainer: How to choose a representative for estate settlement.",
    date: "2026-08-08",
    youtubeId: "NgdZ-dbhua8",
    href: "https://www.youtube.com/watch?v=NgdZ-dbhua8",
    duration: "7:10",
    source: "Legal Guide Philippines",
  },
  {
    id: "lD_5XYifLZI",
    title: "Pano mai-settle ng isang OFW ang kanyang property sa Pinas?",
    description: "A Legal Guide Philippines explainer: Pano mai-settle ng isang OFW ang kanyang property sa Pinas?.",
    date: "2026-08-07",
    youtubeId: "lD_5XYifLZI",
    href: "https://www.youtube.com/watch?v=lD_5XYifLZI",
    duration: "6:25",
    source: "Legal Guide Philippines",
  },
  {
    id: "3_GXMe3Jxyg",
    title: "Paano i-compute ang Estate Tax at Anong Documents ang Needed?",
    description: "A Legal Guide Philippines explainer: Paano i-compute ang Estate Tax at Anong Documents ang Needed?.",
    date: "2026-08-06",
    youtubeId: "3_GXMe3Jxyg",
    href: "https://www.youtube.com/watch?v=3_GXMe3Jxyg",
    duration: "15:57",
    source: "Legal Guide Philippines",
  },
  {
    id: "GENOZcYS4Z0",
    title: "How to transfer Property na nakapangalan pa sa ninuno?",
    description: "A Legal Guide Philippines explainer: How to transfer Property na nakapangalan pa sa ninuno?.",
    date: "2026-08-05",
    youtubeId: "GENOZcYS4Z0",
    href: "https://www.youtube.com/watch?v=GENOZcYS4Z0",
    duration: "15:19",
    source: "Legal Guide Philippines",
  },
  {
    id: "3H9vBDkK20g",
    title: "Is Immediate Resignation Allowed?",
    description: "A Legal Guide Philippines explainer: Is Immediate Resignation Allowed?.",
    date: "2026-08-04",
    youtubeId: "3H9vBDkK20g",
    href: "https://www.youtube.com/watch?v=3H9vBDkK20g",
    duration: "7:09",
    source: "Legal Guide Philippines",
  },
  {
    id: "hfpUVx1xSsg",
    title: "3 Tips if your Family Procrastinating in setlling your Estate Taxes",
    description: "A Legal Guide Philippines explainer: 3 Tips if your Family Procrastinating in setlling your Estate Taxes.",
    date: "2026-08-03",
    youtubeId: "hfpUVx1xSsg",
    href: "https://www.youtube.com/watch?v=hfpUVx1xSsg",
    duration: "6:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "LZ98IHij_TY",
    title: "Ano nga ba ang Estate Tax Amnesty?",
    description: "A Legal Guide Philippines explainer: Ano nga ba ang Estate Tax Amnesty?.",
    date: "2026-08-02",
    youtubeId: "LZ98IHij_TY",
    href: "https://www.youtube.com/watch?v=LZ98IHij_TY",
    duration: "7:49",
    source: "Legal Guide Philippines",
  },
  {
    id: "B-c4io_qgiY",
    title: "Paano mo ibebenta ang property ng namatay mong kamaganak?",
    description: "A Legal Guide Philippines explainer: Paano mo ibebenta ang property ng namatay mong kamaganak?.",
    date: "2026-08-01",
    youtubeId: "B-c4io_qgiY",
    href: "https://www.youtube.com/watch?v=B-c4io_qgiY",
    duration: "8:27",
    source: "Legal Guide Philippines",
  },
  {
    id: "8lrrevVfeb0",
    title: "Paano maiiwasan ang disputes among heirs sa Estate Settlement?",
    description: "A Legal Guide Philippines explainer: Paano maiiwasan ang disputes among heirs sa Estate Settlement?.",
    date: "2026-07-31",
    youtubeId: "8lrrevVfeb0",
    href: "https://www.youtube.com/watch?v=8lrrevVfeb0",
    duration: "6:06",
    source: "Legal Guide Philippines",
  },
  {
    id: "wRPGCo0n7dE",
    title: "Bakit mahirap Mag disiplina ng Empleyado sa Pilipinas?",
    description: "A Legal Guide Philippines explainer: Bakit mahirap Mag disiplina ng Empleyado sa Pilipinas?.",
    date: "2026-07-30",
    youtubeId: "wRPGCo0n7dE",
    href: "https://www.youtube.com/watch?v=wRPGCo0n7dE",
    duration: "4:26",
    source: "Legal Guide Philippines",
  },
  {
    id: "jga1rFxE4XI",
    title: "Preventive suspension: Powerful tool for employers in the Philippines",
    description: "A Legal Guide Philippines explainer: Preventive suspension: Powerful tool for employers in the Philippines.",
    date: "2026-07-29",
    youtubeId: "jga1rFxE4XI",
    href: "https://www.youtube.com/watch?v=jga1rFxE4XI",
    duration: "5:46",
    source: "Legal Guide Philippines",
  },
  {
    id: "sX81gI1mufQ",
    title: "Paano makakatulong ang Incident Reports (I.R.) to properly address work violations?",
    description: "A Legal Guide Philippines explainer: Paano makakatulong ang Incident Reports (I.R.) to properly address work violations?.",
    date: "2026-07-28",
    youtubeId: "sX81gI1mufQ",
    href: "https://www.youtube.com/watch?v=sX81gI1mufQ",
    duration: "4:06",
    source: "Legal Guide Philippines",
  },
  {
    id: "7G3VOqNGHdg",
    title: "Ano ba ang SPA (Special Power of Attorney)?",
    description: "A Legal Guide Philippines explainer: Ano ba ang SPA (Special Power of Attorney)?.",
    date: "2026-07-27",
    youtubeId: "7G3VOqNGHdg",
    href: "https://www.youtube.com/watch?v=7G3VOqNGHdg",
    duration: "6:04",
    source: "Legal Guide Philippines",
  },
  {
    id: "QtHuTGXDMIA",
    title: "Terminal Leave: Pwede bang mag leave ang nag resign na empleyado during turnover period?",
    description: "A Legal Guide Philippines explainer: Terminal Leave: Pwede bang mag leave ang nag resign na empleyado during turnover period?.",
    date: "2026-07-26",
    youtubeId: "QtHuTGXDMIA",
    href: "https://www.youtube.com/watch?v=QtHuTGXDMIA",
    duration: "5:49",
    source: "Legal Guide Philippines",
  },
  {
    id: "uRcHEDfrKgs",
    title: "Ano ang best time to issue Company Policies?",
    description: "A Legal Guide Philippines explainer: Ano ang best time to issue Company Policies?.",
    date: "2026-07-25",
    youtubeId: "uRcHEDfrKgs",
    href: "https://www.youtube.com/watch?v=uRcHEDfrKgs",
    duration: "5:55",
    source: "Legal Guide Philippines",
  },
  {
    id: "CaFJ6o_LkWg",
    title: "Business Owners... Ano ang kailangang tandaan sa darating na January?",
    description: "A Legal Guide Philippines explainer: Business Owners... Ano ang kailangang tandaan sa darating na January?.",
    date: "2026-07-24",
    youtubeId: "CaFJ6o_LkWg",
    href: "https://www.youtube.com/watch?v=CaFJ6o_LkWg",
    duration: "26:57",
    source: "Legal Guide Philippines",
  },
  {
    id: "eRrL5uyrxFI",
    title: "Freelancer o Business Owner man... Ano ang kailangang tandaan pagpasok ng bagong taon?",
    description: "A Legal Guide Philippines explainer: Freelancer o Business Owner man... Ano ang kailangang tandaan pagpasok ng bagong taon?.",
    date: "2026-07-23",
    youtubeId: "eRrL5uyrxFI",
    href: "https://www.youtube.com/watch?v=eRrL5uyrxFI",
    duration: "26:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "0b8XXEqIDyw",
    title: "Ano ang pinagkaiba ng retirement sa resignation?",
    description: "A Legal Guide Philippines explainer: Ano ang pinagkaiba ng retirement sa resignation?.",
    date: "2026-07-22",
    youtubeId: "0b8XXEqIDyw",
    href: "https://www.youtube.com/watch?v=0b8XXEqIDyw",
    duration: "26:48",
    source: "Legal Guide Philippines",
  },
  {
    id: "KOAEmNhWo-I",
    title: "Pwede ka ba sisantihin kapag nakalimutan mo i-declare ang 'yong previous employment?",
    description: "A Legal Guide Philippines explainer: Pwede ka ba sisantihin kapag nakalimutan mo i-declare ang 'yong previous employment?.",
    date: "2026-07-21",
    youtubeId: "KOAEmNhWo-I",
    href: "https://www.youtube.com/watch?v=KOAEmNhWo-I",
    duration: "26:23",
    source: "Legal Guide Philippines",
  },
  {
    id: "6tl7s_pHMLs",
    title: "Violation ba kapag tinanggal ka sa trabaho ng walang \"Due Process\"?",
    description: "A Legal Guide Philippines explainer: Violation ba kapag tinanggal ka sa trabaho ng walang \"Due Process\"?.",
    date: "2026-07-20",
    youtubeId: "6tl7s_pHMLs",
    href: "https://www.youtube.com/watch?v=6tl7s_pHMLs",
    duration: "26:34",
    source: "Legal Guide Philippines",
  },
  {
    id: "xdXHBt2K0LU",
    title: "Pwede bang i-waive ang property na minana? Taxable ba ito?",
    description: "A Legal Guide Philippines explainer: Pwede bang i-waive ang property na minana? Taxable ba ito?.",
    date: "2026-07-19",
    youtubeId: "xdXHBt2K0LU",
    href: "https://www.youtube.com/watch?v=xdXHBt2K0LU",
    duration: "27:08",
    source: "Legal Guide Philippines",
  },
  {
    id: "cIYOX19beug",
    title: "Ano ang pwedeng gawin kung plano mong makipag hiwalay sa partner mo?",
    description: "A Legal Guide Philippines explainer: Ano ang pwedeng gawin kung plano mong makipag hiwalay sa partner mo?.",
    date: "2026-07-18",
    youtubeId: "cIYOX19beug",
    href: "https://www.youtube.com/watch?v=cIYOX19beug",
    duration: "29:45",
    source: "Legal Guide Philippines",
  },
  {
    id: "Y0Y5oFJ9AnM",
    title: "Maari bang bawiin ang lupa na binigay ng magulang mo?",
    description: "A Legal Guide Philippines explainer: Maari bang bawiin ang lupa na binigay ng magulang mo?.",
    date: "2026-07-17",
    youtubeId: "Y0Y5oFJ9AnM",
    href: "https://www.youtube.com/watch?v=Y0Y5oFJ9AnM",
    duration: "27:32",
    source: "Legal Guide Philippines",
  },
  {
    id: "WTNLRo6RUic",
    title: "Can they require me to stay beyond the turnover period?",
    description: "A Legal Guide Philippines explainer: Can they require me to stay beyond the turnover period?.",
    date: "2026-07-16",
    youtubeId: "WTNLRo6RUic",
    href: "https://www.youtube.com/watch?v=WTNLRo6RUic",
    duration: "26:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "XyOZgJ7N03c",
    title: "Anu-ano ang mga dapat asikasuhin kung magpatakbo ka ng negosyo?",
    description: "A Legal Guide Philippines explainer: Anu-ano ang mga dapat asikasuhin kung magpatakbo ka ng negosyo?.",
    date: "2026-07-15",
    youtubeId: "XyOZgJ7N03c",
    href: "https://www.youtube.com/watch?v=XyOZgJ7N03c",
    duration: "27:51",
    source: "Legal Guide Philippines",
  },
  {
    id: "-HkLZ20UPcU",
    title: "Reclaimed Land? Sino ba ang tinatawag na may-ari?",
    description: "A Legal Guide Philippines explainer: Reclaimed Land? Sino ba ang tinatawag na may-ari?.",
    date: "2026-07-14",
    youtubeId: "-HkLZ20UPcU",
    href: "https://www.youtube.com/watch?v=-HkLZ20UPcU",
    duration: "26:03",
    source: "Legal Guide Philippines",
  },
  {
    id: "bxVfTZOARfM",
    title: "Required ba pumirma ng quitclaim or waiver?",
    description: "A Legal Guide Philippines explainer: Required ba pumirma ng quitclaim or waiver?.",
    date: "2026-07-13",
    youtubeId: "bxVfTZOARfM",
    href: "https://www.youtube.com/watch?v=bxVfTZOARfM",
    duration: "23:08",
    source: "Legal Guide Philippines",
  },
  {
    id: "7xA21adFUdI",
    title: "What should you consider when starting a business?",
    description: "A Legal Guide Philippines explainer: What should you consider when starting a business?.",
    date: "2026-07-12",
    youtubeId: "7xA21adFUdI",
    href: "https://www.youtube.com/watch?v=7xA21adFUdI",
    duration: "27:25",
    source: "Legal Guide Philippines",
  },
  {
    id: "Fl-ay0RnSGo",
    title: "What happens if  there's property sold without a deed of sale?",
    description: "A Legal Guide Philippines explainer: What happens if  there's property sold without a deed of sale?.",
    date: "2026-07-11",
    youtubeId: "Fl-ay0RnSGo",
    href: "https://www.youtube.com/watch?v=Fl-ay0RnSGo",
    duration: "29:44",
    source: "Legal Guide Philippines",
  },
  {
    id: "0oe5fYUI3KQ",
    title: "Can a regular employee be terminated due to poor performance?",
    description: "A Legal Guide Philippines explainer: Can a regular employee be terminated due to poor performance?.",
    date: "2026-07-10",
    youtubeId: "0oe5fYUI3KQ",
    href: "https://www.youtube.com/watch?v=0oe5fYUI3KQ",
    duration: "27:17",
    source: "Legal Guide Philippines",
  },
  {
    id: "exez1BOH400",
    title: "What should you look out for when buying condominium in the Philippines?",
    description: "A Legal Guide Philippines explainer: What should you look out for when buying condominium in the Philippines?.",
    date: "2026-07-09",
    youtubeId: "exez1BOH400",
    href: "https://www.youtube.com/watch?v=exez1BOH400",
    duration: "26:44",
    source: "Legal Guide Philippines",
  },
  {
    id: "rniiFTgashY",
    title: "Can a Foreign Pinoy still inherit property from relatives?",
    description: "A Legal Guide Philippines explainer: Can a Foreign Pinoy still inherit property from relatives?.",
    date: "2026-07-08",
    youtubeId: "rniiFTgashY",
    href: "https://www.youtube.com/watch?v=rniiFTgashY",
    duration: "27:28",
    source: "Legal Guide Philippines",
  },
  {
    id: "Wb8-E0Oh7mw",
    title: "Can an employee be fired for having extramarital affairs at workplace?",
    description: "A Legal Guide Philippines explainer: Can an employee be fired for having extramarital affairs at workplace?.",
    date: "2026-07-07",
    youtubeId: "Wb8-E0Oh7mw",
    href: "https://www.youtube.com/watch?v=Wb8-E0Oh7mw",
    duration: "27:31",
    source: "Legal Guide Philippines",
  },
  {
    id: "Ix9hGitZ3Oc",
    title: "Should I donate my properties to my children while I am still alive?",
    description: "A Legal Guide Philippines explainer: Should I donate my properties to my children while I am still alive?.",
    date: "2026-07-06",
    youtubeId: "Ix9hGitZ3Oc",
    href: "https://www.youtube.com/watch?v=Ix9hGitZ3Oc",
    duration: "24:41",
    source: "Legal Guide Philippines",
  },
  {
    id: "KUqPjeSc7ro",
    title: "Can you suspend an employee while there's an ongoing investigation (PREVENTIVE SUSPENSION)?",
    description: "A Legal Guide Philippines explainer: Can you suspend an employee while there's an ongoing investigation (PREVENTIVE SUSPENSION)?.",
    date: "2026-07-05",
    youtubeId: "KUqPjeSc7ro",
    href: "https://www.youtube.com/watch?v=KUqPjeSc7ro",
    duration: "27:57",
    source: "Legal Guide Philippines",
  },
  {
    id: "uYTkNMNcrbY",
    title: "How should you pay the estate taxes of your deceased parents?",
    description: "A Legal Guide Philippines explainer: How should you pay the estate taxes of your deceased parents?.",
    date: "2026-07-04",
    youtubeId: "uYTkNMNcrbY",
    href: "https://www.youtube.com/watch?v=uYTkNMNcrbY",
    duration: "29:03",
    source: "Legal Guide Philippines",
  },
  {
    id: "ewxZKjQyuOA",
    title: "Can a former filipino own land in the Philippines?",
    description: "A Legal Guide Philippines explainer: Can a former filipino own land in the Philippines?.",
    date: "2026-07-03",
    youtubeId: "ewxZKjQyuOA",
    href: "https://www.youtube.com/watch?v=ewxZKjQyuOA",
    duration: "26:10",
    source: "Legal Guide Philippines",
  },
  {
    id: "qwEZkgB2UwI",
    title: "What should you do when you've lost your land title?",
    description: "A Legal Guide Philippines explainer: What should you do when you've lost your land title?.",
    date: "2026-07-02",
    youtubeId: "qwEZkgB2UwI",
    href: "https://www.youtube.com/watch?v=qwEZkgB2UwI",
    duration: "26:19",
    source: "Legal Guide Philippines",
  },
  {
    id: "cjCDdAp6fKE",
    title: "Can an illegitimate child inherit from grandparents?",
    description: "A Legal Guide Philippines explainer: Can an illegitimate child inherit from grandparents?.",
    date: "2026-07-01",
    youtubeId: "cjCDdAp6fKE",
    href: "https://www.youtube.com/watch?v=cjCDdAp6fKE",
    duration: "25:38",
    source: "Legal Guide Philippines",
  },
  {
    id: "Vl0gCJSD7zQ",
    title: "What if someone claims that they own your land?",
    description: "A Legal Guide Philippines explainer: What if someone claims that they own your land?.",
    date: "2026-06-30",
    youtubeId: "Vl0gCJSD7zQ",
    href: "https://www.youtube.com/watch?v=Vl0gCJSD7zQ",
    duration: "26:32",
    source: "Legal Guide Philippines",
  },
  {
    id: "ZA4jdtyjGTc",
    title: "Getting terminated due to negligence",
    description: "A Legal Guide Philippines explainer: Getting terminated due to negligence.",
    date: "2026-06-29",
    youtubeId: "ZA4jdtyjGTc",
    href: "https://www.youtube.com/watch?v=ZA4jdtyjGTc",
    duration: "27:35",
    source: "Legal Guide Philippines",
  },
  {
    id: "U67Hwhp0Eks",
    title: "If a property is given to you, does it also belong to your spouse?",
    description: "A Legal Guide Philippines explainer: If a property is given to you, does it also belong to your spouse?.",
    date: "2026-06-28",
    youtubeId: "U67Hwhp0Eks",
    href: "https://www.youtube.com/watch?v=U67Hwhp0Eks",
    duration: "28:07",
    source: "Legal Guide Philippines",
  },
  {
    id: "xk-HiBdEzLE",
    title: "If a property is given to you, does it also belong to your spouse?",
    description: "A Legal Guide Philippines explainer: If a property is given to you, does it also belong to your spouse?.",
    date: "2026-06-27",
    youtubeId: "xk-HiBdEzLE",
    href: "https://www.youtube.com/watch?v=xk-HiBdEzLE",
    duration: "28:07",
    source: "Legal Guide Philippines",
  },
  {
    id: "Ttxo9HSQOTE",
    title: "Dealing with Mental Health issues at work with Coach Aileen Santos",
    description: "A Legal Guide Philippines explainer: Dealing with Mental Health issues at work with Coach Aileen Santos.",
    date: "2026-06-26",
    youtubeId: "Ttxo9HSQOTE",
    href: "https://www.youtube.com/watch?v=Ttxo9HSQOTE",
    duration: "29:27",
    source: "Legal Guide Philippines",
  },
  {
    id: "WOjne4kSfEw",
    title: "Guide to voting for a President and Vice President",
    description: "A Legal Guide Philippines explainer: Guide to voting for a President and Vice President.",
    date: "2026-06-25",
    youtubeId: "WOjne4kSfEw",
    href: "https://www.youtube.com/watch?v=WOjne4kSfEw",
    duration: "26:28",
    source: "Legal Guide Philippines",
  },
  {
    id: "zUwguTz_zvE",
    title: "What do Senators and Congressmen do for you?",
    description: "A Legal Guide Philippines explainer: What do Senators and Congressmen do for you?.",
    date: "2026-06-24",
    youtubeId: "zUwguTz_zvE",
    href: "https://www.youtube.com/watch?v=zUwguTz_zvE",
    duration: "27:36",
    source: "Legal Guide Philippines",
  },
  {
    id: "jRW1ExTdOkM",
    title: "How to choose the right Governor, Mayor, Counselor, and Board Member this election.",
    description: "A Legal Guide Philippines explainer: How to choose the right Governor, Mayor, Counselor, and Board Member this election..",
    date: "2026-06-23",
    youtubeId: "jRW1ExTdOkM",
    href: "https://www.youtube.com/watch?v=jRW1ExTdOkM",
    duration: "26:53",
    source: "Legal Guide Philippines",
  },
  {
    id: "y32IZ-yo20c",
    title: "How Do Barangay Officials Help You",
    description: "A Legal Guide Philippines explainer: How Do Barangay Officials Help You.",
    date: "2026-06-22",
    youtubeId: "y32IZ-yo20c",
    href: "https://www.youtube.com/watch?v=y32IZ-yo20c",
    duration: "25:00",
    source: "Legal Guide Philippines",
  },
  {
    id: "CuXbpCi_S9c",
    title: "How does the Philippine government work?",
    description: "A Legal Guide Philippines explainer: How does the Philippine government work?.",
    date: "2026-06-21",
    youtubeId: "CuXbpCi_S9c",
    href: "https://www.youtube.com/watch?v=CuXbpCi_S9c",
    duration: "26:29",
    source: "Legal Guide Philippines",
  },
  {
    id: "lmQn-s1JlF0",
    title: "How to write a professional resume",
    description: "A Legal Guide Philippines explainer: How to write a professional resume.",
    date: "2026-06-20",
    youtubeId: "lmQn-s1JlF0",
    href: "https://www.youtube.com/watch?v=lmQn-s1JlF0",
    duration: "27:54",
    source: "Legal Guide Philippines",
  },
  {
    id: "4X3rLAHwozo",
    title: "5 Tips if you're recruiting an employee with StackPH",
    description: "A Legal Guide Philippines explainer: 5 Tips if you're recruiting an employee with StackPH.",
    date: "2026-06-19",
    youtubeId: "4X3rLAHwozo",
    href: "https://www.youtube.com/watch?v=4X3rLAHwozo",
    duration: "27:58",
    source: "Legal Guide Philippines",
  },
  {
    id: "lID-QKI4kjE",
    title: "Are You A Dummy  Incorporator?",
    description: "A Legal Guide Philippines explainer: Are You A Dummy  Incorporator?.",
    date: "2026-06-18",
    youtubeId: "lID-QKI4kjE",
    href: "https://www.youtube.com/watch?v=lID-QKI4kjE",
    duration: "27:04",
    source: "Legal Guide Philippines",
  },
  {
    id: "IIy3NuMyg8c",
    title: "What am I entitled to if I resign now?",
    description: "A Legal Guide Philippines explainer: What am I entitled to if I resign now?.",
    date: "2026-06-17",
    youtubeId: "IIy3NuMyg8c",
    href: "https://www.youtube.com/watch?v=IIy3NuMyg8c",
    duration: "26:51",
    source: "Legal Guide Philippines",
  },
  {
    id: "K0zPJ26Adh0",
    title: "Tips for dealing with your Kasambahay",
    description: "A Legal Guide Philippines explainer: Tips for dealing with your Kasambahay.",
    date: "2026-06-16",
    youtubeId: "K0zPJ26Adh0",
    href: "https://www.youtube.com/watch?v=K0zPJ26Adh0",
    duration: "27:22",
    source: "Legal Guide Philippines",
  },
  {
    id: "644LlqYu3mY",
    title: "Do We Really Need To Notarize?",
    description: "A Legal Guide Philippines explainer: Do We Really Need To Notarize?.",
    date: "2026-06-15",
    youtubeId: "644LlqYu3mY",
    href: "https://www.youtube.com/watch?v=644LlqYu3mY",
    duration: "26:52",
    source: "Legal Guide Philippines",
  },
  {
    id: "O8c8aAp6KGs",
    title: "Putting Your Properties In The Name Of Your Kids",
    description: "A Legal Guide Philippines explainer: Putting Your Properties In The Name Of Your Kids.",
    date: "2026-06-14",
    youtubeId: "O8c8aAp6KGs",
    href: "https://www.youtube.com/watch?v=O8c8aAp6KGs",
    duration: "26:42",
    source: "Legal Guide Philippines",
  },
  {
    id: "3sO6j7BcNPM",
    title: "Can the employee leave earlier if they complete the turnover before the 30 day period?",
    description: "A Legal Guide Philippines explainer: Can the employee leave earlier if they complete the turnover before the 30 day period?.",
    date: "2026-06-13",
    youtubeId: "3sO6j7BcNPM",
    href: "https://www.youtube.com/watch?v=3sO6j7BcNPM",
    duration: "27:20",
    source: "Legal Guide Philippines",
  },
  {
    id: "83Q4FEq83hM",
    title: "How to terminate employees properly?",
    description: "A Legal Guide Philippines explainer: How to terminate employees properly?.",
    date: "2026-06-12",
    youtubeId: "83Q4FEq83hM",
    href: "https://www.youtube.com/watch?v=83Q4FEq83hM",
    duration: "27:43",
    source: "Legal Guide Philippines",
  },
  {
    id: "TTnX4Ff8F5g",
    title: "What are employees supposed to do during the turnover period?",
    description: "A Legal Guide Philippines explainer: What are employees supposed to do during the turnover period?.",
    date: "2026-06-11",
    youtubeId: "TTnX4Ff8F5g",
    href: "https://www.youtube.com/watch?v=TTnX4Ff8F5g",
    duration: "27:02",
    source: "Legal Guide Philippines",
  },
  {
    id: "E3JRkjgS41Q",
    title: "What if there was no employment contract given?",
    description: "A Legal Guide Philippines explainer: What if there was no employment contract given?.",
    date: "2026-06-10",
    youtubeId: "E3JRkjgS41Q",
    href: "https://www.youtube.com/watch?v=E3JRkjgS41Q",
    duration: "26:54",
    source: "Legal Guide Philippines",
  },
  {
    id: "tGc0VweCgF4",
    title: "How To Choose A Business Partner",
    description: "A Legal Guide Philippines explainer: How To Choose A Business Partner.",
    date: "2026-06-09",
    youtubeId: "tGc0VweCgF4",
    href: "https://www.youtube.com/watch?v=tGc0VweCgF4",
    duration: "27:40",
    source: "Legal Guide Philippines",
  },
  {
    id: "-Q_Ro9LVJLU",
    title: "What is contract to sell",
    description: "A Legal Guide Philippines explainer: What is contract to sell.",
    date: "2026-06-08",
    youtubeId: "-Q_Ro9LVJLU",
    href: "https://www.youtube.com/watch?v=-Q_Ro9LVJLU",
    duration: "26:46",
    source: "Legal Guide Philippines",
  },
  {
    id: "s-KONDTe6Vw",
    title: "What you need to know about the Estate Tax Amnesty",
    description: "A Legal Guide Philippines explainer: What you need to know about the Estate Tax Amnesty.",
    date: "2026-06-07",
    youtubeId: "s-KONDTe6Vw",
    href: "https://www.youtube.com/watch?v=s-KONDTe6Vw",
    duration: "26:29",
    source: "Legal Guide Philippines",
  },
  {
    id: "wwy1O8TxS6U",
    title: "Help I need an SPA - How do you make one?",
    description: "A Legal Guide Philippines explainer: Help I need an SPA - How do you make one?.",
    date: "2026-06-06",
    youtubeId: "wwy1O8TxS6U",
    href: "https://www.youtube.com/watch?v=wwy1O8TxS6U",
    duration: "27:06",
    source: "Legal Guide Philippines",
  },
  {
    id: "K-4m_BJvjGI",
    title: "Buying property from someone who has already died.",
    description: "A Legal Guide Philippines explainer: Buying property from someone who has already died..",
    date: "2026-06-05",
    youtubeId: "K-4m_BJvjGI",
    href: "https://www.youtube.com/watch?v=K-4m_BJvjGI",
    duration: "25:12",
    source: "Legal Guide Philippines",
  },
  {
    id: "-AXLh2qZTEI",
    title: "Can employees with pending cases resign?",
    description: "A Legal Guide Philippines explainer: Can employees with pending cases resign?.",
    date: "2026-06-04",
    youtubeId: "-AXLh2qZTEI",
    href: "https://www.youtube.com/watch?v=-AXLh2qZTEI",
    duration: "24:17",
    source: "Legal Guide Philippines",
  },
  {
    id: "KqPpotcH8ks",
    title: "It's sad to belong to a second family (when the estate comes along)",
    description: "A Legal Guide Philippines explainer: It's sad to belong to a second family (when the estate comes along).",
    date: "2026-06-03",
    youtubeId: "KqPpotcH8ks",
    href: "https://www.youtube.com/watch?v=KqPpotcH8ks",
    duration: "23:53",
    source: "Legal Guide Philippines",
  },
  {
    id: "hSdfkCyHA5g",
    title: "Affidavit of Loss Finally Explained",
    description: "A Legal Guide Philippines explainer: Affidavit of Loss Finally Explained.",
    date: "2026-06-02",
    youtubeId: "hSdfkCyHA5g",
    href: "https://www.youtube.com/watch?v=hSdfkCyHA5g",
    duration: "16:36",
    source: "Legal Guide Philippines",
  },
  {
    id: "ZeN7XHVYSoA",
    title: "There's a will, now what?",
    description: "A Legal Guide Philippines explainer: There's a will, now what?.",
    date: "2026-06-01",
    youtubeId: "ZeN7XHVYSoA",
    href: "https://www.youtube.com/watch?v=ZeN7XHVYSoA",
    duration: "25:15",
    source: "Legal Guide Philippines",
  },
  {
    id: "eZl67fV_NUY",
    title: "3 Tips for Making a Code of Discipline",
    description: "A Legal Guide Philippines explainer: 3 Tips for Making a Code of Discipline.",
    date: "2026-05-31",
    youtubeId: "eZl67fV_NUY",
    href: "https://www.youtube.com/watch?v=eZl67fV_NUY",
    duration: "20:00",
    source: "Legal Guide Philippines",
  },
  {
    id: "K2dOqnlDKCk",
    title: "0 - Legal Roadtrip Onboarding",
    description: "A Legal Guide Philippines explainer: 0 - Legal Roadtrip Onboarding.",
    date: "2026-05-30",
    youtubeId: "K2dOqnlDKCk",
    href: "https://www.youtube.com/watch?v=K2dOqnlDKCk",
    duration: "20:21",
    source: "Legal Guide Philippines",
  },
  {
    id: "vNMJvzTyDzk",
    title: "Tips on How to Get Started on Estate Settlement",
    description: "A Legal Guide Philippines explainer: Tips on How to Get Started on Estate Settlement.",
    date: "2026-05-29",
    youtubeId: "vNMJvzTyDzk",
    href: "https://www.youtube.com/watch?v=vNMJvzTyDzk",
    duration: "22:40",
    source: "Legal Guide Philippines",
  },
  {
    id: "19EarMn93gY",
    title: "Can the employee get their final pay without getting a clearance?",
    description: "A Legal Guide Philippines explainer: Can the employee get their final pay without getting a clearance?.",
    date: "2026-05-28",
    youtubeId: "19EarMn93gY",
    href: "https://www.youtube.com/watch?v=19EarMn93gY",
    duration: "17:24",
    source: "Legal Guide Philippines",
  },
  {
    id: "RVV2-_BszL8",
    title: "Who are the VIP's of Estate Settlement",
    description: "A Legal Guide Philippines explainer: Who are the VIP's of Estate Settlement.",
    date: "2026-05-27",
    youtubeId: "RVV2-_BszL8",
    href: "https://www.youtube.com/watch?v=RVV2-_BszL8",
    duration: "20:40",
    source: "Legal Guide Philippines",
  },
  {
    id: "BZ7wMkJhufg",
    title: "Why do Filipinos feel embarrassed when asking someone to sign a contract?",
    description: "A Legal Guide Philippines explainer: Why do Filipinos feel embarrassed when asking someone to sign a contract?.",
    date: "2026-05-26",
    youtubeId: "BZ7wMkJhufg",
    href: "https://www.youtube.com/watch?v=BZ7wMkJhufg",
    duration: "17:26",
    source: "Legal Guide Philippines",
  },
  {
    id: "s4BW0Pivsds",
    title: "When can I ask for separation pay from my employer?",
    description: "A Legal Guide Philippines explainer: When can I ask for separation pay from my employer?.",
    date: "2026-05-25",
    youtubeId: "s4BW0Pivsds",
    href: "https://www.youtube.com/watch?v=s4BW0Pivsds",
    duration: "23:33",
    source: "Legal Guide Philippines",
  },
  {
    id: "0wi9eBXdXRQ",
    title: "Can You Extend the Probationary Period",
    description: "A Legal Guide Philippines explainer: Can You Extend the Probationary Period.",
    date: "2026-05-24",
    youtubeId: "0wi9eBXdXRQ",
    href: "https://www.youtube.com/watch?v=0wi9eBXdXRQ",
    duration: "14:44",
    source: "Legal Guide Philippines",
  },
  {
    id: "1Q1cp6ADbJo",
    title: "Contract of Sale vs. Deed of Donation. Which should you choose?",
    description: "A Legal Guide Philippines explainer: Contract of Sale vs. Deed of Donation. Which should you choose?.",
    date: "2026-05-23",
    youtubeId: "1Q1cp6ADbJo",
    href: "https://www.youtube.com/watch?v=1Q1cp6ADbJo",
    duration: "19:43",
    source: "Legal Guide Philippines",
  },
  {
    id: "o0e8AP9XeG4",
    title: "How you can get into trouble by sharing too much information",
    description: "A Legal Guide Philippines explainer: How you can get into trouble by sharing too much information.",
    date: "2026-05-22",
    youtubeId: "o0e8AP9XeG4",
    href: "https://www.youtube.com/watch?v=o0e8AP9XeG4",
    duration: "15:10",
    source: "Legal Guide Philippines",
  },
  {
    id: "Fa3nRqC9d_Q",
    title: "4 Things to Consider in Starting a Company",
    description: "A Legal Guide Philippines explainer: 4 Things to Consider in Starting a Company.",
    date: "2026-05-21",
    youtubeId: "Fa3nRqC9d_Q",
    href: "https://www.youtube.com/watch?v=Fa3nRqC9d_Q",
    duration: "12:02",
    source: "Legal Guide Philippines",
  },
  {
    id: "m_78rHkJ0MI",
    title: "When should you demote employees?",
    description: "A Legal Guide Philippines explainer: When should you demote employees?.",
    date: "2026-05-20",
    youtubeId: "m_78rHkJ0MI",
    href: "https://www.youtube.com/watch?v=m_78rHkJ0MI",
    duration: "17:30",
    source: "Legal Guide Philippines",
  },
  {
    id: "kczTVfi3EKg",
    title: "3 Powerful Guidelines to Manage AWOL Cases",
    description: "A Legal Guide Philippines explainer: 3 Powerful Guidelines to Manage AWOL Cases.",
    date: "2026-05-19",
    youtubeId: "kczTVfi3EKg",
    href: "https://www.youtube.com/watch?v=kczTVfi3EKg",
    duration: "10:51",
    source: "Legal Guide Philippines",
  },
  {
    id: "aLNBccu1jBA",
    title: "How To Make a Probationary Contract Like a Lawyer",
    description: "A Legal Guide Philippines explainer: How To Make a Probationary Contract Like a Lawyer.",
    date: "2026-05-18",
    youtubeId: "aLNBccu1jBA",
    href: "https://www.youtube.com/watch?v=aLNBccu1jBA",
    duration: "11:10",
    source: "Legal Guide Philippines",
  },
  {
    id: "9gjMNS71GPc",
    title: "3 Mistakes Bosses Make When Making a Certificate of Employment",
    description: "A Legal Guide Philippines explainer: 3 Mistakes Bosses Make When Making a Certificate of Employment.",
    date: "2026-05-17",
    youtubeId: "9gjMNS71GPc",
    href: "https://www.youtube.com/watch?v=9gjMNS71GPc",
    duration: "14:41",
    source: "Legal Guide Philippines",
  },
  {
    id: "YYMjn-gPIo8",
    title: "Ask page for Legal Guide",
    description: "A Legal Guide Philippines explainer: Ask page for Legal Guide.",
    date: "2026-05-16",
    youtubeId: "YYMjn-gPIo8",
    href: "https://www.youtube.com/watch?v=YYMjn-gPIo8",
    duration: "2:20",
    source: "Legal Guide Philippines",
  },
  {
    id: "9sqjXJJOexY",
    title: "Tips for Drafting a Notice to Explain",
    description: "A Legal Guide Philippines explainer: Tips for Drafting a Notice to Explain.",
    date: "2026-05-15",
    youtubeId: "9sqjXJJOexY",
    href: "https://www.youtube.com/watch?v=9sqjXJJOexY",
    duration: "10:26",
    source: "Legal Guide Philippines",
  },
  {
    id: "oq7FQYuKDRM",
    title: "Can I immediately resign and leave my work?",
    description: "A Legal Guide Philippines explainer: Can I immediately resign and leave my work?.",
    date: "2026-05-14",
    youtubeId: "oq7FQYuKDRM",
    href: "https://www.youtube.com/watch?v=oq7FQYuKDRM",
    duration: "12:48",
    source: "Legal Guide Philippines",
  },
  {
    id: "i-ZxIAYFTtQ",
    title: "Do you need estate settlement if the inheritance is small?",
    description: "A Legal Guide Philippines explainer: Do you need estate settlement if the inheritance is small?.",
    date: "2026-05-13",
    youtubeId: "i-ZxIAYFTtQ",
    href: "https://www.youtube.com/watch?v=i-ZxIAYFTtQ",
    duration: "6:39",
    source: "Legal Guide Philippines",
  },
  {
    id: "fjBpnAp0ZMw",
    title: "Resignation Video",
    description: "A Legal Guide Philippines explainer: Resignation Video.",
    date: "2026-05-12",
    youtubeId: "fjBpnAp0ZMw",
    href: "https://www.youtube.com/watch?v=fjBpnAp0ZMw",
    duration: "1:48",
    source: "Legal Guide Philippines",
  },
  {
    id: "KILjI5sPlk0",
    title: "Welcome to the Legal Guide Show",
    description: "A Legal Guide Philippines explainer: Welcome to the Legal Guide Show.",
    date: "2026-05-11",
    youtubeId: "KILjI5sPlk0",
    href: "https://www.youtube.com/watch?v=KILjI5sPlk0",
    duration: "4:53",
    source: "Legal Guide Philippines",
  },
  {
    id: "zFYAZH2LH9E",
    title: "Estate Settlement Video",
    description: "A Legal Guide Philippines explainer: Estate Settlement Video.",
    date: "2026-05-10",
    youtubeId: "zFYAZH2LH9E",
    href: "https://www.youtube.com/watch?v=zFYAZH2LH9E",
    duration: "2:40",
    source: "Legal Guide Philippines",
  },
  {
    id: "suipu39q2HQ",
    title: "About us - Legal Guide",
    description: "A Legal Guide Philippines explainer: About us - Legal Guide.",
    date: "2026-05-09",
    youtubeId: "suipu39q2HQ",
    href: "https://www.youtube.com/watch?v=suipu39q2HQ",
    duration: "4:39",
    source: "Legal Guide Philippines",
  },
];

export function getVideos(): Video[] {
  return [...videos].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
  );
}

export function getFeaturedVideos(limit = 2): Video[] {
  return getVideos().slice(0, limit);
}

export function getVideoById(id: string): Video | undefined {
  return videos.find((v) => v.id === id || v.youtubeId === id);
}

export function getRelatedVideos(id: string, limit = 4): Video[] {
  return getVideos().filter((v) => v.id !== id).slice(0, limit);
}

export function getAllVideoIds(): string[] {
  return videos.map((v) => v.id);
}
